apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: handmade

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: handmade-backend
  app.kubernetes.io/part-of: handmade-ecommerce
  app.kubernetes.io/managed-by: kustomize

images:
  - name: handmade-backend
    newName: handmade-backend
    newTag: latest
