spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME:handmade}?currentSchema=homebase_uat
    username: ${DB_USERNAME:homebase_uat_rw}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: homebase_uat
    enabled: true
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: homebase_uat

logging:
  level:
    liquibase: INFO
